AZURE_LOCATION: 'eastus2'
RESOURCE_NAME_PREFIX: 'apimlz'
ENVIRONMENT_TAG: 'pr'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/devivasudevan'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
