AZURE_LOCATION: 'eastus2'
RESOURCE_NAME_PREFIX: 'apim'
ENVIRONMENT_TAG: 'prod'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'https://github.com/devivasudevan'
CICD_AGENT_TYPE: 'github'
CERT_TYPE: 'selfsigned'
