AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'apim'
ENVIRONMENT_TAG: 'prod'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'github.com/devivasudevan'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
